version: "3"
services:
  database:
    hostname: database
    image: postgres:15.1-alpine
    # restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ead45021a2dc0195c9cb07840961a219
    ports:
      - 5432:5432
    volumes:
      - elof_database:/var/lib/postgresql/data
    networks:
      nw:
        aliases:
          - database
  bot:
      restart: always
      hostname: alert.com
      build: ./
      command: /srv/telegram_admin/run.sh
      environment:
        - DATABASE_URL=database
        - DATABASE_PASSWORD=ead45021a2dc0195c9cb07840961a219
        - DATABASE_USER=postgres
        - DATABASE_PORT=5432
        - TABLE_NAME=alb
        - BOT_TOKEN=6074772635:AAFKTvl-_QgcqELoSW6PAacEj5eAQvVb2QM
        - DEBUG=False
        - SERVER=True
        - DOMAIN=alert-bot.hikmatillo.ru
      ports:
        - "88:88"
      depends_on:
        - database
      networks:
        nw:
          aliases:
            - bot

networks:
  nw:
  share:
    driver:
      bridge

volumes:
  elof_database:

