# Generated by Django 4.1.3 on 2023-04-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('telegram_id',
                 models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID     ^b         ^`    ')),
                ('nickname', models.TextField(verbose_name=' ^}            ')),
                ('full_name', models.TextField(verbose_name='   ^x ^~')),
                ('email', models.TextField(verbose_name=' ^=   ^g ^b  ')),
                ('notify', models.BooleanField(default=False,
                                               verbose_name='^a ^b   ^b ^c ^a            ^g')),
            ],
            options={
                'verbose_name': ' ^p              ^b  ',
                'verbose_name_plural': ' ^p         ^k      ^b  ',
            },
        ),
    ]
