# Generated by Django 4.1.3 on 2023-04-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('telegram_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID в телеграм')),
                ('nickname', models.TextField(verbose_name='Никнейм')),
                ('full_name', models.TextField(verbose_name='ФИО')),
                ('email', models.TextField(verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Админ бота',
                'verbose_name_plural': 'Админы бота',
            },
        ),
    ]
