# Generated by Django 4.1.3 on 2023-04-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertBot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='notify',
            field=models.BooleanField(default=False, verbose_name='Уведомление о статусе задач'),
        ),
    ]
